name: Label By comment
on: issue_comment

jobs:
  add_comment_labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Label issue
        uses: ./
        with:
          token: ${{secrets.REPO_TOKEN}}
          action: labels_by_user_input
