name: PR Actions
on: pull_request_target

jobs:
  initial_assignments:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Remove Verified Label
        uses: ./
        with:
          token: ${{secrets.REPO_TOKEN}}
          action: remove_verified_label

      - name: Assign Size Labels
        uses: ./
        with:
          token: ${{secrets.REPO_TOKEN}}
          reviewers: myakove
          action: size_label_prs

      - name: Assign Reviewers
        uses: ./
        with:
          token: ${{secrets.REPO_TOKEN}}
          reviewers: myakove,rnetser,AdiZav
          action: add_reviewers

      - name: Block Merge (No Verified Label)
        uses: ./
        with:
          token: ${{secrets.REPO_TOKEN}}
          action: block_merge_no_verify
